### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by bregman-arie** [redhat-openstack/ansible-nfv#1]
I would like to send patches to this repo. Can you please let me know how to contribute? (PR? GerritHub?)

I think it's also a good idea to add it to the documentation.

**Comment by Yarboa** [comment]
Hi Arie

With pleasure, we welcome every contribute.
Maxim Babushkin  ans Eyal Danon responsible to manage this repo

Thank you
Yariv

**Comment by bregman-arie** [comment]
k, great. @MaxBab @edannon can you tell me how should I contribute to this project? pull requests or some review system?
